// <auto-generated />
namespace SapatosWPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migracao41 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migracao41));
        
        string IMigrationMetadata.Id
        {
            get { return "201806171545373_migracao41"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
