// <auto-generated />
namespace SapatosWPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migracao3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migracao3));
        
        string IMigrationMetadata.Id
        {
            get { return "201806170442263_migracao3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
